
import "./globals.css";
import Navbar from "../components/navbar";
import Providers from "../components/Providers";
import variables from '../styles/variables.module.scss'




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className='h-screen' style={{backgroundColor:variables.primaryColor}}>
      <Providers>
        <Navbar />
        {children}
      </Providers>
        </body>
       
    </html>
  );
}
